Tensors are multidimensional arrays similar to numpy arrays (or pytorch tensors). There are numerous builtin operations ranging from addition to matrix inversion. 

Big differences between numpy arrays and tensors:

- tensors can be backed by accelerator memory (e.g. GPU, TPU)
- tensors are immutable



Conversions:

- tf operations automatically convert numpy arrays to tensors
- numpy operations automatically convert tensors to numpy arrays


can convert a tensor to numpy array using `.numpy()`


## Device names

- tensors have a fully qualified string name of the device hosting the conents of the tensor, even the network address of the host for distributed training.

can do explicit device placement using the context manager

```python
with tf.device("GPU:0"):
    x = tf.random.uniform([1000, 1000])

```


### Creating a source dataset

In [2]:
import tensorflow as tf

ds_tensors = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])

# create a CSV file
import tempfile
_, filename = tempfile.mkstemp()

with open(filename, "w") as f:
    f.write("""Line 1
Line 2
Line 3
  """)

ds_file = tf.data.TextLineDataset(filename)

2023-08-02 08:36:45.610367: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-02 08:36:45.650309: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-02 08:36:45.650976: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-02 08:36:46.399720: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


### apply transformations

In [6]:
ds_tensors = ds_tensors.map(tf.math.square).shuffle(2).batch(2)

ds_file = ds_file.batch(2)

Iterate

In [8]:
print('Elements of ds_tensors:')
for x in ds_tensors:
    print(x)

print('\nElements in ds_file:')
for x in ds_file:
    print(x)

Elements of ds_tensors:
tf.Tensor(
[[  16  625]
 [ 256 1296]], shape=(2, 2), dtype=int32)
tf.Tensor([[ 1 81]], shape=(1, 2), dtype=int32)

Elements in ds_file:
tf.Tensor(
[[b'Line 1' b'Line 2']
 [b'Line 3' b'  ']], shape=(2, 2), dtype=string)


# References

- https://www.tensorflow.org/tutorials/customization/basics